name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
    - name: Restore dependencies
      run: |
        dotnet restore ./FmsSimulator/FmsSimulator.csproj
        dotnet restore ./FmsSimulator.Tests/FmsSimulator.Tests.csproj
    - name: Build main project
      run: dotnet build ./FmsSimulator/FmsSimulator.csproj --no-restore --configuration Release
    - name: Build test project
      run: dotnet build ./FmsSimulator.Tests/FmsSimulator.Tests.csproj --no-restore --configuration Release
    - name: Run tests
      run: dotnet test ./FmsSimulator.Tests/FmsSimulator.Tests.csproj --no-build --configuration Release --verbosity normal
